### ISSUE TITLE
.status field present in CRDs

### ISSUE THREAD

**Issue by daurnimator** [coreos/kube-prometheus#586]
In the CRD definitions, the trailing field (`.status) is set, e.g.  https://github.com/coreos/kube-prometheus/blame/de9591cbb07ec4c2a3d3f95d5526753ea4247f08/manifests/setup/prometheus-operator-0thanosrulerCustomResourceDefinition.yaml#L4854-L4859

This makes the kustomization permanently dirty when trying to apply to a cluster.

Please remove the `.status` fields from the CRDs.

**Comment by brancz** [comment]
This is unfortunately how the CRD generation tools generate them. I believe @pgier had looked into this somewhat recently. Is there an issue on the generation tools to get this fixed?

**Comment by daurnimator** [comment]
> Is there an issue on the generation tools to get this fixed?

which generation tools do you mean?

**Comment by dgrisonnet** [comment]
We are using [controller-gen](https://book.kubebuilder.io/reference/controller-gen.html) to generate the CRDs. The issue was fixed in https://github.com/kubernetes-sigs/controller-tools/pull/433 but AFAIK this patch has not been released yet.

That being said, there is another issue with controller-gen generating invalid CRDs in k8s 1.18 that prevent us from bumping its version. So, even if the patch removing the status field land in the next release, we might not be able to bump controller-gen in prometheus-operator.

**Comment by morgante** [comment]
Status is still present: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/setup/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml#L84

Unfortunately it looks like controller-gen hasn't stripped this yet: https://github.com/kubernetes-sigs/controller-tools/issues/456

**Comment by paulfantom** [comment]
This needs to be fixed in controller-tools, until then you can apply a quick and dirty hack in jsonnet code:

```
    prometheusOperator+: {
      "0alertmanagerConfigCustomResourceDefinition"+: {
        status:: null,
      },
      "0alertmanagerCustomResourceDefinition"+: {
        status:: null,
      },
      "0podMonitorCustomResourceDefinition"+: {
        status:: null,
      },
      "0probeCustomResourceDefinition"+: {
        status:: null,
      },
      "0prometheusCustomResourceDefinition"+: {
        status:: null,
      },
      "0prometheusruleCustomResourceDefinition"+: {
        status:: null,
      },
      "0servicemonitorCustomResourceDefinition"+: {
        status:: null,
      },
      "0thanosrulerCustomResourceDefinition"+: {
        status:: null,
      },
    },
```
